### ISSUE TITLE
Unable to use npm package

### ISSUE THREAD

**Issue by saraivinha85** [halvardssm/package-translation-fetch#1]
Hi, i'm trying to use package-translation-fetch within my project.
I added the dependency and a new script to package.json like it says on the readme:

scripts: {
  "translations": "translation-fetch"
}

After running "yarn translations" I get:
"/bin/sh: translation-fetch: Command not found"

**Comment by halvardssm** [comment]
Hi @saraivinha85 ! Thanks for reporting this bug! There was an issue with the publishing part of the CI which was fixed in #2 . The new version is `v0.1.11` 👍
